In [ ]:
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [ ]:
BiocManager::install("DESeq2")

'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cran.rstudio.com

Bioconductor version 3.23 (BiocManager 1.30.27), R 4.6.0 (2026-04-24)

Installing package(s) 'BiocVersion', 'DESeq2'

also installing the dependencies ‘XVector’, ‘formatR’, ‘abind’, ‘SparseArray’, ‘lambda.r’, ‘futile.options’, ‘Seqinfo’, ‘S4Arrays’, ‘DelayedArray’, ‘futile.logger’, ‘snow’, ‘BH’, ‘S4Vectors’, ‘IRanges’, ‘GenomicRanges’, ‘SummarizedExperiment’, ‘BiocGenerics’, ‘Biobase’, ‘BiocParallel’, ‘matrixStats’, ‘locfit’, ‘MatrixGenerics’, ‘RcppArmadillo’


Old packages: 'bit64', 'broom', 'bslib', 'openssl', 'readxl', 'xtable'

In [ ]:
library("DESeq2")

Loading required package: S4Vectors

Loading required package: stats4

Loading required package: BiocGenerics

Loading required package: generics


Attaching package: ‘generics’


The following objects are masked from ‘package:base’:

    as.difftime, as.factor, as.ordered, intersect, is.element, setdiff,
    setequal, union



Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, saveRDS, table, tapply, unique,
    unsplit, which.max, which.min



Attaching package: ‘S4Vectors’


The following object is masked from ‘package:utils’:

    findMatches


The following objects are masked from ‘package:base’:

    expand.grid, I, unname


Loading required package: IRanges

Loading required package: GenomicRanges

Loading required package: Seqinfo

Loading required package: SummarizedExperiment

Loading required package: MatrixGenerics

Loading required package: matrixStats


Attaching package: ‘MatrixGenerics’


The following objects are masked from ‘package:matrixStats’:

    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,
    colCounts, colCummaxs, colCummins, colCumprods, colCumsums,
    colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,
    colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,
    colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,
    colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,
    colWeightedMeans, colWeightedMedians, colWeightedSds,
    colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,
    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,
    rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,
    rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,
    rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,
    rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,
    rowWeightedMads, rowWeightedMeans, rowWeightedMedians,
    rowWeightedSds, rowWeightedVars


Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.



Attaching package: ‘Biobase’


The following object is masked from ‘package:MatrixGenerics’:

    rowMedians


The following objects are masked from ‘package:matrixStats’:

    anyMissing, rowMedians

In [ ]:
#### Import the dds obtained from nfcore/rnaseq ####
countData <- as.matrix(read.csv("/content/UC.csv", row.names = 1, header = TRUE, sep = ","))

In [ ]:
colData <- read.csv("/content/UC_metadata.csv", row.names = 1, header = TRUE, sep = ",")

In [ ]:
all(colnames(countData) == rownames(colData))

[1] TRUE

In [ ]:
dds <- DESeqDataSetFromMatrix(countData = countData,
                              colData = colData,
                              design = ~ group)

ERROR: Error in DESeqDataSet(se, design = design, ignoreRank): some values in assay are not integers

In [ ]:
head(countData)

       GSE36807_GSM901319_Control GSE36807_GSM901320_Control
DDR1   10.057815                  10.240368
RFC2    7.006085                   7.280890
HSPA6   4.869625                   4.930321
PAX8    6.931251                   7.581242
GUCA1A  2.779867                   3.069317
THRA    4.432978                   4.380786
       GSE36807_GSM901321_Control GSE36807_GSM901322_Control
DDR1   10.333251                  10.274616
RFC2    6.833791                   7.059975
HSPA6   4.602452                   4.444003
PAX8    7.490506                   7.546182
GUCA1A  2.989712                   3.106594
THRA    4.408092                   4.410836
       GSE36807_GSM901323_Control GSE36807_GSM901324_Control
DDR1   10.193718                  10.345840
RFC2    6.888110                   6.471107
HSPA6   4.545595                   4.944784
PAX8    7.391695                   7.443755
GUCA1A  3.008654                   3.026941
THRA    4.526112                   4.501738
       GSE36807_GSM901325_Control GSE36807_GSM901339_Treat
DDR1   10.258877                  7.736802
RFC2    7.023984                  7.496996
HSPA6   4.866114                  5.804740
PAX8    7.646819                  6.673034
GUCA1A  2.987807                  2.983185
THRA    4.453489                  4.239220
       GSE36807_GSM901340_Treat GSE36807_GSM901341_Treat ⋯
DDR1   10.094271                9.294401                 ⋯
RFC2    7.208984                7.514114                 ⋯
HSPA6   4.728608                5.226530                 ⋯
PAX8    7.501456                7.293650                 ⋯
GUCA1A  2.987456                2.980563                 ⋯
THRA    3.970315                4.107714                 ⋯
       GSE92415_GSM2429494_Treat GSE92415_GSM2429495_Treat
DDR1   9.995451                  10.410198
RFC2   6.700711                   7.323427
HSPA6  6.525598                   6.638938
PAX8   6.493281                   7.214686
GUCA1A 3.345456                   3.531410
THRA   6.460510                   7.152021
       GSE92415_GSM2429496_Treat GSE92415_GSM2429497_Treat
DDR1   9.464461                  9.098340
RFC2   8.337286                  7.914607
HSPA6  7.685391                  8.753466
PAX8   6.172379                  6.245204
GUCA1A 3.483778                  3.364656
THRA   7.378832                  7.204249
       GSE92415_GSM2429498_Treat GSE92415_GSM2429499_Treat
DDR1   10.388133                 9.089467
RFC2    7.867744                 7.792481
HSPA6   6.764330                 7.156074
PAX8    6.478995                 6.586063
GUCA1A  3.392893                 3.439477
THRA    7.256009                 6.889370
       GSE92415_GSM2429500_Treat GSE92415_GSM2429501_Treat
DDR1   9.574879                  10.006680
RFC2   7.701057                   7.595404
HSPA6  6.823591                   6.385248
PAX8   6.727793                   6.053946
GUCA1A 3.328430                   3.548217
THRA   7.125814                   7.700865
       GSE92415_GSM2429502_Treat GSE92415_GSM2429503_Treat
DDR1   10.274535                 10.339688
RFC2    7.556081                  8.061285
HSPA6   8.118005                  7.046505
PAX8    6.975910                  6.545643
GUCA1A  3.496870                  3.560906
THRA    7.259819                  6.692713

In [ ]:
library(limma)

ERROR: Error in library(limma): there is no package called ‘limma’

In [ ]:
install.packages("limma")
library(limma)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Warning message:
“package ‘limma’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages”

ERROR: Error in library(limma): there is no package called ‘limma’

In [ ]:
countData <- as.matrix(

  read.csv(

    "/content/GSE89408_raw_RNA-seq_counts.csv",

    row.names = 1,

    header = TRUE,

    sep = ","

  )

)

ERROR: Error in h(simpleError(msg, call)): error in evaluating the argument 'x' in selecting a method for function 'as.matrix': duplicate 'row.names' are not allowed

In [ ]:
countData <- read.csv(
  "/content/GSE89408_raw_RNA-seq_counts.csv",
  header = TRUE,
  sep = ",",
  check.names = FALSE
)

rownames(countData) <- make.unique(as.character(countData[,1]))

countData <- countData[,-1]

countData <- as.matrix(countData)

In [ ]:
head(countData)

                    normal_tissue_1 normal_tissue_2 normal_tissue_3
5S_rRNA               0.00            0.00             0.0
7SK                 472.59          897.97          1127.7
7SK:ENSG00000260682  17.41           37.03            89.3
A1BG                 45.00           15.00            19.0
A1BG-AS1             96.00           13.00            25.0
A1CF                  0.00            1.00             0.0
                    normal_tissue_4 normal_tissue_5 normal_tissue_6
5S_rRNA               0.0             0.0             0.0
7SK                 441.8           363.9           291.5
7SK:ENSG00000260682  27.2            78.1           118.5
A1BG                 29.0            32.0            15.0
A1BG-AS1             99.0            80.0            70.0
A1CF                  0.0             0.0             0.0
                    normal_tissue_7 normal_tissue_8 normal_tissue_9
5S_rRNA                0.0            0.00           0
7SK                 1032.7          670.37           0
7SK:ENSG00000260682   64.3           69.63           0
A1BG                  19.0           39.00          43
A1BG-AS1              59.0          105.00           0
A1CF                   0.0            0.00           0
                    normal_tissue_10 ⋯ RA_tissue_143 RA_tissue_144
5S_rRNA               0.00           ⋯    0.0           0.00
7SK                 509.55           ⋯ 2250.2        3708.41
7SK:ENSG00000260682  30.45           ⋯  156.8         116.59
A1BG                105.00           ⋯   12.0          29.00
A1BG-AS1            129.00           ⋯   34.0          42.00
A1CF                  0.00           ⋯    1.0           0.00
                    RA_tissue_145 RA_tissue_146 RA_tissue_147 RA_tissue_148
5S_rRNA                1.00          1.0           1.00          1.00
7SK                 1335.70       2533.7        1960.84       3278.89
7SK:ENSG00000260682   93.30        125.3         123.16        123.11
A1BG                  15.00         27.0          30.00         28.24
A1BG-AS1               9.03         89.0          71.00         62.00
A1CF                  53.00          0.0           0.00          0.00
                    RA_tissue_149 RA_tissue_150 RA_tissue_151 RA_tissue_152
5S_rRNA                0.00          0.00          1.00          0.00
7SK                 1094.61       3539.28       1145.43       1164.43
7SK:ENSG00000260682  115.39         93.72        105.57        117.57
A1BG                  45.00         40.00         55.00         15.00
A1BG-AS1             103.00         83.00        170.00         57.00
A1CF                   1.00          0.00          2.00          0.00

In [ ]:
all(colnames(countData) == rownames(colData))

Warning message in colnames(countData) == rownames(colData):
“longer object length is not a multiple of shorter object length”

[1] FALSE

In [ ]:
colnames(countData)

  [1] "normal_tissue_1"  "normal_tissue_2"  "normal_tissue_3"
  [4] "normal_tissue_4"  "normal_tissue_5"  "normal_tissue_6"
  [7] "normal_tissue_7"  "normal_tissue_8"  "normal_tissue_9"
 [10] "normal_tissue_10" "normal_tissue_11" "normal_tissue_12"
 [13] "normal_tissue_13" "normal_tissue_14" "normal_tissue_15"
 [16] "normal_tissue_16" "normal_tissue_17" "normal_tissue_18"
 [19] "normal_tissue_19" "normal_tissue_20" "normal_tissue_21"
 [22] "normal_tissue_22" "normal_tissue_23" "normal_tissue_24"
 [25] "normal_tissue_25" "normal_tissue_26" "normal_tissue_27"
 [28] "normal_tissue_28" "OA_tissue_1"      "OA_tissue_2"
 [31] "OA_tissue_3"      "OA_tissue_4"      "OA_tissue_5"
 [34] "OA_tissue_6"      "OA_tissue_7"      "OA_tissue_8"
 [37] "OA_tissue_9"      "OA_tissue_10"     "OA_tissue_11"
 [40] "OA_tissue_12"     "OA_tissue_13"     "OA_tissue_14"
 [43] "OA_tissue_15"     "OA_tissue_16"     "OA_tissue_17"
 [46] "OA_tissue_18"     "OA_tissue_19"     "OA_tissue_20"
 [49] "OA_tissue_21"     "OA_tissue_22"     "AG_tissue_1"
 [52] "AG_tissue_2"      "AG_tissue_3"      "AG_tissue_4"
 [55] "AG_tissue_5"      "AG_tissue_6"      "AG_tissue_7"
 [58] "AG_tissue_8"      "AG_tissue_9"      "AG_tissue_10"
 [61] "undiff_tissue_1"  "undiff_tissue_2"  "undiff_tissue_3"
 [64] "undiff_tissue_4"  "undiff_tissue_5"  "undiff_tissue_6"
 [67] "RA_tissue_1"      "RA_tissue_2"      "RA_tissue_3"
 [70] "RA_tissue_4"      "RA_tissue_5"      "RA_tissue_6"
 [73] "RA_tissue_7"      "RA_tissue_8"      "RA_tissue_9"
 [76] "RA_tissue_10"     "RA_tissue_11"     "RA_tissue_12"
 [79] "RA_tissue_13"     "RA_tissue_14"     "RA_tissue_15"
 [82] "RA_tissue_16"     "RA_tissue_17"     "RA_tissue_18"
 [85] "RA_tissue_19"     "RA_tissue_20"     "RA_tissue_21"
 [88] "RA_tissue_22"     "RA_tissue_23"     "RA_tissue_24"
 [91] "RA_tissue_25"     "RA_tissue_26"     "RA_tissue_27"
 [94] "RA_tissue_28"     "RA_tissue_29"     "RA_tissue_30"
 [97] "RA_tissue_31"     "RA_tissue_32"     "RA_tissue_33"
[100] "RA_tissue_34"     "RA_tissue_35"     "RA_tissue_36"
[103] "RA_tissue_37"     "RA_tissue_38"     "RA_tissue_39"
[106] "RA_tissue_40"     "RA_tissue_41"     "RA_tissue_42"
[109] "RA_tissue_43"     "RA_tissue_44"     "RA_tissue_45"
[112] "RA_tissue_46"     "RA_tissue_47"     "RA_tissue_48"
[115] "RA_tissue_49"     "RA_tissue_50"     "RA_tissue_51"
[118] "RA_tissue_52"     "RA_tissue_53"     "RA_tissue_54"
[121] "RA_tissue_55"     "RA_tissue_56"     "RA_tissue_57"
[124] "RA_tissue_58"     "RA_tissue_59"     "RA_tissue_60"
[127] "RA_tissue_61"     "RA_tissue_62"     "RA_tissue_63"
[130] "RA_tissue_64"     "RA_tissue_65"     "RA_tissue_66"
[133] "RA_tissue_67"     "RA_tissue_68"     "RA_tissue_69"
[136] "RA_tissue_70"     "RA_tissue_71"     "RA_tissue_72"
[139] "RA_tissue_73"     "RA_tissue_74"     "RA_tissue_75"
[142] "RA_tissue_76"     "RA_tissue_77"     "RA_tissue_78"
[145] "RA_tissue_79"     "RA_tissue_80"     "RA_tissue_81"
[148] "RA_tissue_82"     "RA_tissue_83"     "RA_tissue_84"
[151] "RA_tissue_85"     "RA_tissue_86"     "RA_tissue_87"
[154] "RA_tissue_88"     "RA_tissue_89"     "RA_tissue_90"
[157] "RA_tissue_91"     "RA_tissue_92"     "RA_tissue_93"
[160] "RA_tissue_94"     "RA_tissue_95"     "RA_tissue_96"
[163] "RA_tissue_97"     "RA_tissue_98"     "RA_tissue_99"
[166] "RA_tissue_100"    "RA_tissue_101"    "RA_tissue_102"
[169] "RA_tissue_103"    "RA_tissue_104"    "RA_tissue_105"
[172] "RA_tissue_106"    "RA_tissue_107"    "RA_tissue_108"
[175] "RA_tissue_109"    "RA_tissue_110"    "RA_tissue_111"
[178] "RA_tissue_112"    "RA_tissue_113"    "RA_tissue_114"
[181] "RA_tissue_115"    "RA_tissue_116"    "RA_tissue_117"
[184] "RA_tissue_118"    "RA_tissue_119"    "RA_tissue_120"
[187] "RA_tissue_121"    "RA_tissue_122"    "RA_tissue_123"
[190] "RA_tissue_124"    "RA_tissue_125"    "RA_tissue_126"
[193] "RA_tissue_127"    "RA_tissue_128"    "RA_tissue_129"
[196] "RA_tissue_130"    "RA_tissue_131"    "RA_tissue_132"
[199] "RA_tissue_133"    "RA_tissue_134"    "RA_tissue_135"
[202] "RA_tissue_136"    "RA_tissue_137"    "RA_tissue_138"
[205] "RA_tissue_139"    "RA_tissue_140"    "RA_tissue_141"
[208] "RA_tissue_142"    "RA_tissue_143"    "RA_tissue_144"
[211] "RA_tissue_145"    "RA_tissue_146"    "RA_tissue_147"
[214] "RA_tissue_148"    "RA_tissue_149"    "RA_tissue_150"
[217] "RA_tissue_151"    "RA_tissue_152"

In [ ]:
rownames(colData)

  [1] "GSE36807_GSM901319_Control"  "GSE36807_GSM901320_Control"
  [3] "GSE36807_GSM901321_Control"  "GSE36807_GSM901322_Control"
  [5] "GSE36807_GSM901323_Control"  "GSE36807_GSM901324_Control"
  [7] "GSE36807_GSM901325_Control"  "GSE36807_GSM901339_Treat"
  [9] "GSE36807_GSM901340_Treat"    "GSE36807_GSM901341_Treat"
 [11] "GSE36807_GSM901342_Treat"    "GSE36807_GSM901343_Treat"
 [13] "GSE36807_GSM901344_Treat"    "GSE36807_GSM901345_Treat"
 [15] "GSE36807_GSM901346_Treat"    "GSE36807_GSM901347_Treat"
 [17] "GSE36807_GSM901348_Treat"    "GSE36807_GSM901349_Treat"
 [19] "GSE36807_GSM901350_Treat"    "GSE36807_GSM901351_Treat"
 [21] "GSE36807_GSM901352_Treat"    "GSE36807_GSM901353_Treat"
 [23] "GSE87473_GSM2332098_Control" "GSE87473_GSM2332099_Control"
 [25] "GSE87473_GSM2332100_Control" "GSE87473_GSM2332101_Control"
 [27] "GSE87473_GSM2332102_Control" "GSE87473_GSM2332103_Control"
 [29] "GSE87473_GSM2332104_Control" "GSE87473_GSM2332105_Control"
 [31] "GSE87473_GSM2332106_Control" "GSE87473_GSM2332107_Control"
 [33] "GSE87473_GSM2332108_Control" "GSE87473_GSM2332109_Control"
 [35] "GSE87473_GSM2332110_Control" "GSE87473_GSM2332111_Control"
 [37] "GSE87473_GSM2332112_Control" "GSE87473_GSM2332113_Control"
 [39] "GSE87473_GSM2332114_Control" "GSE87473_GSM2332115_Control"
 [41] "GSE87473_GSM2332116_Control" "GSE87473_GSM2332117_Control"
 [43] "GSE87473_GSM2332118_Control" "GSE87473_GSM2332079_Treat"
 [45] "GSE87473_GSM2332080_Treat"   "GSE87473_GSM2332081_Treat"
 [47] "GSE87473_GSM2332082_Treat"   "GSE87473_GSM2332083_Treat"
 [49] "GSE87473_GSM2332084_Treat"   "GSE87473_GSM2332085_Treat"
 [51] "GSE87473_GSM2332086_Treat"   "GSE87473_GSM2332087_Treat"
 [53] "GSE87473_GSM2332088_Treat"   "GSE87473_GSM2332089_Treat"
 [55] "GSE87473_GSM2332090_Treat"   "GSE87473_GSM2332091_Treat"
 [57] "GSE87473_GSM2332092_Treat"   "GSE87473_GSM2332093_Treat"
 [59] "GSE87473_GSM2332094_Treat"   "GSE87473_GSM2332095_Treat"
 [61] "GSE87473_GSM2332096_Treat"   "GSE87473_GSM2332097_Treat"
 [63] "GSE87473_GSM2332119_Treat"   "GSE87473_GSM2332120_Treat"
 [65] "GSE87473_GSM2332121_Treat"   "GSE87473_GSM2332122_Treat"
 [67] "GSE87473_GSM2332123_Treat"   "GSE87473_GSM2332124_Treat"
 [69] "GSE87473_GSM2332125_Treat"   "GSE87473_GSM2332126_Treat"
 [71] "GSE87473_GSM2332127_Treat"   "GSE87473_GSM2332128_Treat"
 [73] "GSE87473_GSM2332129_Treat"   "GSE87473_GSM2332130_Treat"
 [75] "GSE87473_GSM2332131_Treat"   "GSE87473_GSM2332132_Treat"
 [77] "GSE87473_GSM2332133_Treat"   "GSE87473_GSM2332134_Treat"
 [79] "GSE87473_GSM2332135_Treat"   "GSE87473_GSM2332136_Treat"
 [81] "GSE87473_GSM2332137_Treat"   "GSE87473_GSM2332138_Treat"
 [83] "GSE87473_GSM2332139_Treat"   "GSE87473_GSM2332140_Treat"
 [85] "GSE87473_GSM2332141_Treat"   "GSE87473_GSM2332142_Treat"
 [87] "GSE87473_GSM2332143_Treat"   "GSE87473_GSM2332144_Treat"
 [89] "GSE87473_GSM2332145_Treat"   "GSE87473_GSM2332146_Treat"
 [91] "GSE87473_GSM2332147_Treat"   "GSE87473_GSM2332148_Treat"
 [93] "GSE87473_GSM2332149_Treat"   "GSE87473_GSM2332150_Treat"
 [95] "GSE87473_GSM2332151_Treat"   "GSE87473_GSM2332152_Treat"
 [97] "GSE87473_GSM2332153_Treat"   "GSE87473_GSM2332154_Treat"
 [99] "GSE87473_GSM2332155_Treat"   "GSE87473_GSM2332156_Treat"
[101] "GSE87473_GSM2332157_Treat"   "GSE87473_GSM2332158_Treat"
[103] "GSE87473_GSM2332159_Treat"   "GSE87473_GSM2332160_Treat"
[105] "GSE87473_GSM2332161_Treat"   "GSE87473_GSM2332162_Treat"
[107] "GSE87473_GSM2332163_Treat"   "GSE87473_GSM2332164_Treat"
[109] "GSE87473_GSM2332165_Treat"   "GSE87473_GSM2332166_Treat"
[111] "GSE87473_GSM2332167_Treat"   "GSE87473_GSM2332168_Treat"
[113] "GSE87473_GSM2332169_Treat"   "GSE87473_GSM2332170_Treat"
[115] "GSE87473_GSM2332171_Treat"   "GSE87473_GSM2332172_Treat"
[117] "GSE87473_GSM2332173_Treat"   "GSE87473_GSM2332174_Treat"
[119] "GSE87473_GSM2332175_Treat"   "GSE87473_GSM2332176_Treat"
[121] "GSE87473_GSM2332177_Treat"   "GSE87473_GSM2332178_Treat"
[123] "GSE87473_GSM2332179_Treat"   "GSE87473_GSM2332180_Treat"
[125] "GSE87473_GSM2332181_Treat"   "GSE87473_GSM2332182_Treat"
[127] "GSE87473_GSM2332183_Treat"   "GSE87473_GSM2332184_Treat"
[129] "GSE87473_GSM2332185_Treat"   "GSE87473_GSM2332186_Treat"
[131] "GSE87473_GSM2332187_Treat"   "GSE87473_GSM2332188_Treat"
[133] "GSE87473_GSM2332189_Treat"   "GSE87473_GSM2332190_Treat"
[135] "GSE87473_GSM2332191_Treat"   "GSE87473_GSM2332192_Treat"
[137] "GSE87473_GSM2332193_Treat"   "GSE87473_GSM2332194_Treat"
[139] "GSE87473_GSM2332195_Treat"   "GSE87473_GSM2332196_Treat"
[141] "GSE87473_GSM2332197_Treat"   "GSE87473_GSM2332198_Treat"
[143] "GSE87473_GSM2332199_Treat"   "GSE87473_GSM2332200_Treat"
[145] "GSE87473_GSM2332201_Treat"   "GSE87473_GSM2332202_Treat"
[147] "GSE87473_GSM2332203_Treat"   "GSE87473_GSM2332204_Treat"
[149] "GSE87473_GSM2332205_Treat"   "GSE92415_GSM2429455_Control"
[151] "GSE92415_GSM2429456_Control" "GSE92415_GSM2429457_Control"
[153] "GSE92415_GSM2429458_Control" "GSE92415_GSM2429459_Control"
[155] "GSE92415_GSM2429460_Control" "GSE92415_GSM2429461_Control"
[157] "GSE92415_GSM2429462_Control" "GSE92415_GSM2429463_Control"
[159] "GSE92415_GSM2429464_Control" "GSE92415_GSM2429465_Control"
[161] "GSE92415_GSM2429466_Control" "GSE92415_GSM2429467_Control"
[163] "GSE92415_GSM2429468_Control" "GSE92415_GSM2429469_Control"
[165] "GSE92415_GSM2429470_Control" "GSE92415_GSM2429471_Control"
[167] "GSE92415_GSM2429472_Control" "GSE92415_GSM2429473_Control"
[169] "GSE92415_GSM2429474_Control" "GSE92415_GSM2429475_Control"
[171] "GSE92415_GSM2429346_Treat"   "GSE92415_GSM2429347_Treat"
[173] "GSE92415_GSM2429348_Treat"   "GSE92415_GSM2429349_Treat"
[175] "GSE92415_GSM2429350_Treat"   "GSE92415_GSM2429351_Treat"
[177] "GSE92415_GSM2429352_Treat"   "GSE92415_GSM2429353_Treat"
[179] "GSE92415_GSM2429354_Treat"   "GSE92415_GSM2429355_Treat"
[181] "GSE92415_GSM2429356_Treat"   "GSE92415_GSM2429357_Treat"
[183] "GSE92415_GSM2429358_Treat"   "GSE92415_GSM2429359_Treat"
[185] "GSE92415_GSM2429360_Treat"   "GSE92415_GSM2429361_Treat"
[187] "GSE92415_GSM2429362_Treat"   "GSE92415_GSM2429363_Treat"
[189] "GSE92415_GSM2429364_Treat"   "GSE92415_GSM2429365_Treat"
[191] "GSE92415_GSM2429366_Treat"   "GSE92415_GSM2429367_Treat"
[193] "GSE92415_GSM2429368_Treat"   "GSE92415_GSM2429369_Treat"
[195] "GSE92415_GSM2429370_Treat"   "GSE92415_GSM2429371_Treat"
[197] "GSE92415_GSM2429372_Treat"   "GSE92415_GSM2429373_Treat"
[199] "GSE92415_GSM2429374_Treat"   "GSE92415_GSM2429375_Treat"
[201] "GSE92415_GSM2429376_Treat"   "GSE92415_GSM2429377_Treat"
[203] "GSE92415_GSM2429378_Treat"   "GSE92415_GSM2429379_Treat"
[205] "GSE92415_GSM2429380_Treat"   "GSE92415_GSM2429381_Treat"
[207] "GSE92415_GSM2429382_Treat"   "GSE92415_GSM2429383_Treat"
[209] "GSE92415_GSM2429384_Treat"   "GSE92415_GSM2429385_Treat"
[211] "GSE92415_GSM2429386_Treat"   "GSE92415_GSM2429387_Treat"
[213] "GSE92415_GSM2429388_Treat"   "GSE92415_GSM2429389_Treat"
[215] "GSE92415_GSM2429390_Treat"   "GSE92415_GSM2429391_Treat"
[217] "GSE92415_GSM2429392_Treat"   "GSE92415_GSM2429393_Treat"
[219] "GSE92415_GSM2429394_Treat"   "GSE92415_GSM2429395_Treat"
[221] "GSE92415_GSM2429396_Treat"   "GSE92415_GSM2429397_Treat"
[223] "GSE92415_GSM2429398_Treat"   "GSE92415_GSM2429399_Treat"
[225] "GSE92415_GSM2429400_Treat"   "GSE92415_GSM2429401_Treat"
[227] "GSE92415_GSM2429402_Treat"   "GSE92415_GSM2429403_Treat"
[229] "GSE92415_GSM2429404_Treat"   "GSE92415_GSM2429476_Treat"
[231] "GSE92415_GSM2429477_Treat"   "GSE92415_GSM2429478_Treat"
[233] "GSE92415_GSM2429479_Treat"   "GSE92415_GSM2429480_Treat"
[235] "GSE92415_GSM2429481_Treat"   "GSE92415_GSM2429482_Treat"
[237] "GSE92415_GSM2429483_Treat"   "GSE92415_GSM2429484_Treat"
[239] "GSE92415_GSM2429485_Treat"   "GSE92415_GSM2429486_Treat"
[241] "GSE92415_GSM2429487_Treat"   "GSE92415_GSM2429488_Treat"
[243] "GSE92415_GSM2429489_Treat"   "GSE92415_GSM2429490_Treat"
[245] "GSE92415_GSM2429491_Treat"   "GSE92415_GSM2429492_Treat"
[247] "GSE92415_GSM2429493_Treat"   "GSE92415_GSM2429494_Treat"
[249] "GSE92415_GSM2429495_Treat"   "GSE92415_GSM2429496_Treat"
[251] "GSE92415_GSM2429497_Treat"   "GSE92415_GSM2429498_Treat"
[253] "GSE92415_GSM2429499_Treat"   "GSE92415_GSM2429500_Treat"
[255] "GSE92415_GSM2429501_Treat"   "GSE92415_GSM2429502_Treat"
[257] "GSE92415_GSM2429503_Treat"

In [ ]:
samples <- colnames(countData)

group <- ifelse(grepl("normal|control", samples, ignore.case = TRUE),
                "Control",
                "Disease")

colData <- data.frame(
  row.names = samples,
  group = group
)

head(colData)

                group
normal_tissue_1 Control
normal_tissue_2 Control
normal_tissue_3 Control
normal_tissue_4 Control
normal_tissue_5 Control
normal_tissue_6 Control

In [ ]:
all(colnames(countData) == rownames(colData))

[1] TRUE

In [ ]:
dds <- DESeqDataSetFromMatrix(
  countData = countData,
  colData = colData,
  design = ~ group
)

ERROR: Error in DESeqDataSet(se, design = design, ignoreRank): some values in assay are not integers

In [ ]:
countData <- round(countData)

In [ ]:
dds <- DESeqDataSetFromMatrix(
  countData = countData,
  colData = colData,
  design = ~ group
)

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”

In [ ]:
dds <- DESeq(dds)

estimating size factors

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

final dispersion estimates

fitting model and testing

-- replacing outliers and refitting for 1788 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

estimating dispersions

fitting model and testing

In [ ]:
res <- results(dds)

In [ ]:
head(res)

log2 fold change (MLE): group Disease vs Control
Wald test p-value: group Disease vs Control
DataFrame with 6 rows and 6 columns
                       baseMean log2FoldChange     lfcSE      stat      pvalue
                      <numeric>      <numeric> <numeric> <numeric>   <numeric>
5S_rRNA                0.333284       0.224358  0.661286  0.339276 7.34402e-01
7SK                 1224.675350       1.088462  0.176219  6.176774 6.54247e-10
7SK:ENSG00000260682  167.880381       2.043585  0.231266  8.836513 9.87525e-19
A1BG                  45.196912      -1.512494  0.267536 -5.653429 1.57278e-08
A1BG-AS1              93.515536       0.301037  0.176312  1.707411 8.77457e-02
A1CF                   2.501771       3.019960  1.009523  2.991473 2.77635e-03
                           padj
                      <numeric>
5S_rRNA             7.86334e-01
7SK                 2.39092e-09
7SK:ENSG00000260682 1.01110e-17
A1BG                4.97773e-08
A1BG-AS1            1.23151e-01
A1CF                5.00295e-03

In [ ]:
# =========================
# VOLCANO PLOT
# Differentially Expressed Genes
# =========================

# Load required libraries
library(ggplot2)
library(ggrepel)

# Convert DESeq2 results into a dataframe
res_df <- as.data.frame(res)

# Remove missing values
res_df <- na.omit(res_df)

# Add gene names as a new column
res_df$gene <- rownames(res_df)

# Create significance categories
res_df$group <- "Not Significant"

# Upregulated genes
res_df$group[
  res_df$padj < 0.05 &
  res_df$log2FoldChange > 1
] <- "Upregulated"

# Downregulated genes
res_df$group[
  res_df$padj < 0.05 &
  res_df$log2FoldChange < -1
] <- "Downregulated"

# Select top significant genes for labeling
top_genes <- res_df[
  order(res_df$padj),
][1:15, ]

# Generate volcano plot
ggplot(
  res_df,
  aes(
    x = log2FoldChange,
    y = -log10(padj),
    color = group
  )
) +

# Plot points
geom_point(
  alpha = 0.7,
  size = 2
) +

# Define colors
scale_color_manual(
  values = c(
    "Upregulated" = "red",
    "Downregulated" = "blue",
    "Not Significant" = "gray"
  )
) +

# Add threshold lines
geom_vline(
  xintercept = c(-1, 1),
  linetype = "dashed"
) +

geom_hline(
  yintercept = -log10(0.05),
  linetype = "dashed"
) +

# Add gene labels
geom_text_repel(
  data = top_genes,
  aes(label = gene),
  size = 3,
  max.overlaps = 20
) +

# Apply theme
theme_classic() +

# Add plot labels
labs(
  title = "Volcano Plot of Differentially Expressed Genes",
  subtitle = "Comparison between Disease and Control groups",
  x = "log2 Fold Change",
  y = expression(-log[10]("Adjusted p-value")),
  color = "Gene Category"
)

ERROR: Error in library(ggrepel): there is no package called ‘ggrepel’

In [ ]:
# =========================
# LIBRARIES
# =========================

library(DESeq2)
library(pheatmap)
library(RColorBrewer)

# =========================
# VARIANCE STABILIZATION
# =========================

vsd <- vst(dds)

# =========================
# SELECT TOP GENES
# =========================

topgenes <- head(order(res$padj), 100)

# expression matrix
mat <- assay(vsd)[topgenes, ]

# =========================
# SAMPLE ANNOTATION
# =========================

annotation <- data.frame(
  Type = colData$group
)

rownames(annotation) <- colnames(mat)

# =========================
# ANNOTATION COLORS
# =========================

ann_colors <- list(

  Type = c(
    "Control" = "#BDBD00",
    "Disease" = "#26C6DA"
  )

)

# =========================
# HEATMAP
# =========================

pheatmap(

  mat,

  # normalize each gene
  scale = "row",

  # clustering
  cluster_rows = TRUE,
  cluster_cols = TRUE,

  # annotations
  annotation_col = annotation,
  annotation_colors = ann_colors,

  # heatmap colors
  color = colorRampPalette(
    c("blue", "white", "red")
  )(100),

  # symmetric scale
  breaks = seq(-3, 3, length.out = 101),

  # labels
  show_colnames = FALSE,
  show_rownames = TRUE,

  # font sizes
  fontsize_row = 5,
  fontsize_col = 5,

  # borders
  border_color = "grey85",

  # dendrogram sizes
  treeheight_row = 60,
  treeheight_col = 60

)